name: Build

on: [push]

jobs:
  build-storybook-kit:
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "15.0"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme StorybookKit -sdk iphonesimulator -destination 'generic/platform=iOS Simulator'
  build-storybook-kit-texture-support:
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "15.0"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme StorybookKitTextureSupport -sdk iphonesimulator -destination 'generic/platform=iOS Simulator'
